language: node_js
node_js:
  - "10"

cache:
  yarn: true

install:
  - yarn install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/
  github_token: $GITHUB_TOKEN
  keep_history: false
  name: coolpi21
  email: coolpi07@gmail.com
  on:
    branch: master
